### ISSUE TITLE
Default Populator using a converter to populate a certain related-object

### ISSUE THREAD

**Issue by mike4git** [teamneusta/converter-bundle#15]
In some situations (e.g. a Customer with an Address) you want to populate the related object (here: Address) by using the Converter to convert to target type (e.g. AddressView).

This could be simplified by a default Populator which gets the right Converter injected.
This Populator should be defined in Symfony by the given Converter and the field name.

The same issue exists for a list of related objects of the same type (e.g. Customer could have more Addresses).

**Comment by jdreesen** [comment]
Nice idea. 

We would need some kind of mechanism to determine which converter is the default one for a source object (because there may be multiple, e.g. converting an object for the frontend or for an export). 
Maybe we even need some kind of grouping for this, so that when converting the customer's address for the frontend the `address.converter.frontend` is used and when converting it for an export, the `address.converter.export` is used. 

I think a problem is that we currently don't know (and have no way of determining) which type a converter handles, as they're generic. We could tag the services with the source (and target) types, maybe.

Because of this, I fear that this feature would be tricky to implement, but we'll see.
